# ==============================================================================
# stubs/ndict_tools/__init__.pyi
# ==============================================================================
# Temporary type stubs for ndict-tools (biface/ndt).
#
# ndict-tools 1.2.0 ships no .pyi files, causing basedpyright to mark all
# StrictNestedDictionary attributes and return values as Unknown, which
# cascades into hundreds of warnings throughout i18n-tools.
#
# These stubs cover only the public surface actually used by i18n-tools.
# They are intentionally minimal — correctness over completeness.
#
# REMOVE THIS FILE once ndict-tools >= 1.3.0 ships its own stubs (planned
# for November 2025 alongside the Python 3.10 EOL drop).
# Track: https://github.com/biface/ndt
# ==============================================================================

from typing import Any, Generator, Iterator, Type, TypeVar

_T = TypeVar("_T", bound="_StackedDict")

# ------------------------------------------------------------------------------
# Exceptions
# ------------------------------------------------------------------------------

class NestedDictionaryException(Exception): ...
class StackedDictionaryError(NestedDictionaryException): ...
class StackedKeyError(StackedDictionaryError, KeyError): ...
class StackedAttributeError(StackedDictionaryError, AttributeError): ...
class StackedTypeError(StackedDictionaryError, TypeError): ...
class StackedValueError(StackedDictionaryError, ValueError): ...
class StackedIndexError(StackedDictionaryError, IndexError): ...

# ------------------------------------------------------------------------------
# PathsView / CompactPathsView
# ------------------------------------------------------------------------------

class PathsView:
    def __init__(self, stacked_dict: _StackedDict) -> None: ...
    def __iter__(self) -> Iterator[list[Any]]: ...
    def __len__(self) -> int: ...
    def __contains__(self, path: list[Any]) -> bool: ...
    def get_children(self, path: list[Any]) -> list[Any]: ...
    def get_leaf_paths(self) -> list[list[Any]]: ...
    def to_compact(self) -> CompactPathsView: ...

class CompactPathsView(PathsView):
    @property
    def structure(self) -> list[Any]: ...
    @structure.setter
    def structure(self, value: list[Any]) -> None: ...
    def expand(self) -> list[list[Any]]: ...
    def is_covering(self, stacked_dict: _StackedDict) -> bool: ...
    def coverage(self, stacked_dict: _StackedDict) -> float: ...
    def uncovered_paths(self, stacked_dict: _StackedDict) -> list[list[Any]]: ...
    def to_paths(self) -> PathsView: ...

# ------------------------------------------------------------------------------
# _StackedDict — internal base (not exported, but needed for type hierarchy)
# ------------------------------------------------------------------------------

class _StackedDict(dict[Any, Any]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __len__(self) -> int: ...
    def keys(self) -> Any: ...
    def values(self) -> Any: ...
    def items(self) -> Any: ...
    def to_dict(self) -> dict[Any, Any]: ...
    def ancestors(self, value: Any) -> Any: ...
    def dfs(
        self, node: Any = ..., path: Any = ...
    ) -> Generator[tuple[list[Any], Any], None, None]: ...
    def bfs(self) -> Generator[tuple[tuple[Any, ...], Any], None, None]: ...
    @classmethod
    def from_dict(
        cls: Type[_T], dictionary: dict[Any, Any], **class_options: Any
    ) -> _T: ...

# ------------------------------------------------------------------------------
# Public classes
# ------------------------------------------------------------------------------

class NestedDictionary(_StackedDict):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def paths(self) -> PathsView: ...
    def compact_paths(self) -> CompactPathsView: ...

class StrictNestedDictionary(NestedDictionary):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class SmoothNestedDictionary(NestedDictionary):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

# ------------------------------------------------------------------------------
# Module-level helpers
# ------------------------------------------------------------------------------

def from_dict(
    dictionary: dict[Any, Any], class_name: Type[_T], **class_options: Any
) -> _T: ...

__version__: str
__author__: str

__all__ = [
    "PathsView",
    "CompactPathsView",
    "NestedDictionary",
    "SmoothNestedDictionary",
    "StrictNestedDictionary",
    "NestedDictionaryException",
    "StackedDictionaryError",
    "StackedKeyError",
    "StackedAttributeError",
    "StackedTypeError",
    "StackedValueError",
    "StackedIndexError",
]
